version: 2.1
jobs:
  build:
    docker:
      - image: node:14
    steps:
      - checkout
      - run: 'npm install'
      - run: 'npm run build'
      - run: 'npm run test'

workflows:
  my_workflow:
    jobs:
      - build
