version: 2.1
jobs:
  build:
    docker:
      - image: node:14
    steps:
      - checkout
      - run: 'npm run build'
  test:
    docker:
      - image: node:14
    steps:
      - checkout
      - run: 'npm run test'
